import { NewsArticle, CommunityPost, Quest, Badge, UserRank, User, StockItem, PredictionNews } from './types';

export const initialUser: User = {
  id: 'user_1',
  name: '이슬',
  avatar: '이',
  level: 1,
  xp: 0,
  nextLevelXp: 500,
  streakDays: 0,
  interests: ['반도체', 'AI', '글로벌 증시'],
  readArticlesCount: 0,
  earnedBadgesCount: 0,
  predictionStats: {
    accuracy: 0,
    averageError: 0,
    totalPredictions: 0,
    correctPredictions: 0,
    currentStreak: 0,
    bestStreak: 0,
    rankingScore: 0,
  }
};

export const mockArticles: NewsArticle[] = [
  {
    id: 'art-1',
    category: '반도체',
    readStatus: true,
    title: "NVIDIA, 차세대 AI 칩 '루빈' 양산 일정 앞당긴다",
    source: '연합뉴스 (경제)',
    publishedTime: '2시간 전',
    readTime: '3분 읽기',
    impactRating: 5,
    iconType: 'chip',
    summary: '엔비디아가 블랙웰의 다음 세대인 루빈 AI GPU 양산 타임라인을 2026년 상반기로 단축하여 기술 주도권을 확고히 합니다.',
    likesCount: 15,
    commentsCount: 2,
    comments: [
      {
        id: 'c1',
        authorName: '성공투자자',
        authorAvatar: '성',
        authorLevel: 8,
        content: 'HBM4 수주전이 정말 핵심이겠네요. 4컷 만화로 보니까 이해가 잘 됩니다!',
        createdAt: '45분 전',
        likes: 5,
      },
      {
        id: 'c2',
        authorName: '슬기로운개미',
        authorAvatar: '슬',
        authorLevel: 2,
        content: '루빈 아키텍처 궁금했는데 깔끔하게 요약해주셔서 감사합니다.',
        createdAt: '20분 전',
        likes: 2,
      }
    ],
    keyTakeaways: [
      '차세대 루빈 아키텍처는 HBM4를 탑재하여 연산 속도를 3배 향상시킵니다.',
      '양산 시점이 6개월 앞당겨지면서 관련 반도체 공급망에 큰 호재로 작용합니다.',
      '삼성전자와 SK하이닉스의 HBM4 수주 경쟁이 더욱 치열해질 전망입니다.'
    ],
    cartoonPanels: [
      {
        panelNumber: 1,
        title: '1컷: 속도전 개시!',
        sceneDescription: '엔비디아 CEO 젠슨 황이 루빈 칩 로드맵 서류를 들고 당당하게 서있다.',
        characterSpeaker: '젠슨 황',
        speechBubble: 'AI 시장이 너무 가파르게 성장해요! 차세대 칩 "루빈" 양산을 6개월 앞당깁니다!',
        visualIcon: 'building',
        keyTerm: '루빈 (Rubin)',
        keyTermDefinition: '엔비디아의 차세대 AI 전용 아키텍처로 HBM4 메모리가 탑재될 예정입니다.'
      },
      {
        panelNumber: 2,
        title: '2컷: 왜 앞당길까?',
        sceneDescription: '빅테크 기업들이 AI 데이터센터 서버에 엄청난 돈을 쏟아붓고 있는 그래프.',
        characterSpeaker: '빅테크 수장',
        speechBubble: '더 빠른 AI 처리 속도가 필요해요! 얼른 칩을 공급해주세요!',
        visualIcon: 'handshake',
        keyTerm: 'AI 가속기',
        keyTermDefinition: '딥러닝 연산을 전문적으로 빠르게 처리하기 위해 특화된 반도체 칩셋입니다.'
      },
      {
        panelNumber: 3,
        title: '3컷: 메모리 반도체의 미소',
        sceneDescription: 'SK하이닉스와 삼성전자 캐릭터가 HBM4 메모리를 들고 웃고 있다.',
        characterSpeaker: 'K-반도체',
        speechBubble: '루빈에는 차세대 HBM4가 필수! 우리 고성능 메모리 수요가 폭발하겠네요!',
        visualIcon: 'chart',
        keyTerm: 'HBM4',
        keyTermDefinition: '4세대 고대역폭 메모리로 반도체 칩을 세로로 쌓아 전송 속도를 극대화한 기술입니다.'
      },
      {
        panelNumber: 4,
        title: '4컷: 투자 시장 영향',
        sceneDescription: '주가 그래프가 우상향하며 개미 캐릭터가 돋보기를 들고 분석하는 모습.',
        characterSpeaker: '투자자 개미',
        speechBubble: 'AI 반도체 생태계 전반에 큰 온기가 돌겠군요! 공급망 체인을 주목해봅시다.',
        visualIcon: 'graduation',
        keyTerm: '공급망 (Supply Chain)',
        keyTermDefinition: '제품 생산부터 최종 전달까지의 모든 기업과 프로세스 연결망입니다.'
      }
    ]
  },
  {
    id: 'art-2',
    category: '금리',
    readStatus: true,
    title: "미국 중앙은행, 이번 달 금리 동결... 시장은 '안도'",
    source: '한국경제신문',
    publishedTime: '5시간 전',
    readTime: '4분 읽기',
    impactRating: 4,
    iconType: 'bank',
    summary: '연준이 기준금리를 동결하면서 물가 안정세와 경기 침체 우려 사이에서 균형을 잡았습니다.',
    likesCount: 8,
    commentsCount: 1,
    comments: [
      {
        id: 'c3',
        authorName: '주식왕라이언',
        authorAvatar: '라',
        authorLevel: 4,
        content: '금리 동결로 증시 불확실성이 해소되어 다행입니다. 기술주 흐름 지켜봐야겠어요.',
        createdAt: '1시간 전',
        likes: 3,
      }
    ],
    keyTakeaways: [
      '기준금리가 현 수준인 5.25~5.50%로 유지되었습니다.',
      '인플레이션 지표 하락으로 하반기 금리 인하 가능성이 높아졌습니다.',
      '기술주 위주의 증시가 불확실성 해소로 상승세를 보였습니다.'
    ],
    cartoonPanels: [
      {
        panelNumber: 1,
        title: '1컷: 연준의 결정',
        sceneDescription: '제롬 파월 의장이 망치를 들고 기준금리 동결을 선언하는 장면.',
        characterSpeaker: '파월 의장',
        speechBubble: '이번 금리는 동결입니다! 물가 인하 추세를 좀 더 지켜보겠습니다.',
        visualIcon: 'bank',
        keyTerm: '기준금리',
        keyTermDefinition: '한 국가의 금리 체계의 기준이 되는 정책 금리입니다.'
      },
      {
        panelNumber: 2,
        title: '2컷: 시장의 반응',
        sceneDescription: '상승하는 증시 그래프와 활짝 웃는 주식시장 캐릭터.',
        characterSpeaker: '투자자',
        speechBubble: '금리 인상 위험이 사라졌다! 증시에 숨통이 트이겠군요!',
        visualIcon: 'chart',
        keyTerm: '동결 (Hold)',
        keyTermDefinition: '금리를 올리거나 내리지 않고 현재 수준을 계속 유지함을 뜻합니다.'
      },
      {
        panelNumber: 3,
        title: '3컷: 기술주의 찬스',
        sceneDescription: '기술주 캐릭터들이 신나서 뛰어오르는 모습.',
        characterSpeaker: '빅테크 기업',
        speechBubble: '금리가 안정되면 자금 조달 부담이 줄어들어 기술 투자를 확충할 수 있어요!',
        visualIcon: 'chip',
        keyTerm: '성장주',
        keyTermDefinition: '현재 이익보다 미래의 성장 가능성이 높아 고평가받는 기술 기업들의 주식입니다.'
      },
      {
        panelNumber: 4,
        title: '4컷: 앞으로의 관전 포인트',
        sceneDescription: '다음 연준 통화정책 회의 날짜가 적힌 달력.',
        characterSpeaker: '경제 튜터',
        speechBubble: '다음 회의에서 금리 인하 신호가 나올지가 핵심입니다. 고용지표를 유심히 관찰하세요!',
        visualIcon: 'graduation',
        keyTerm: '인하 시그널',
        keyTermDefinition: '중앙은행이 조만간 금리를 내릴 것임을 암시하는 언론 발표나 발언입니다.'
      }
    ]
  }
];

export const mockCommunityPosts: CommunityPost[] = [
  {
    id: 'post-1',
    title: '엔비디아 루빈 양산 관련 4컷 만화 요약본 공유합니다!',
    category: '반도체',
    authorName: '주식초보라이언',
    authorLevel: 4,
    authorAvatar: '라',
    createdAt: '1시간 전',
    likesCount: 24,
    commentsCount: 6,
    isLiked: false,
    newsTitle: "NVIDIA, 차세대 AI 칩 '루빈' 양산 일정 앞당긴다",
    summary: '엔비디아의 루빈 칩 양산 호재와 한국 메모리 반도체 기업들의 반응을 쉽게 정리했어요.',
    views: 182,
    cartoonPanels: mockArticles[0].cartoonPanels,
    comments: [
      {
        id: 'c1',
        authorName: '성공투자자',
        authorAvatar: '성',
        authorLevel: 8,
        content: 'HBM4 수주전이 정말 핵심이겠네요. 만화로 보니까 한눈에 이해됩니다!',
        createdAt: '45분 전',
        likes: 5,
      },
      {
        id: 'c2',
        authorName: '슬기로운개미',
        authorAvatar: '슬',
        authorLevel: 2,
        content: '루빈 아키텍처 궁금했는데 깔끔하게 요약해주셔서 감사합니다.',
        createdAt: '20분 전',
        likes: 2,
      }
    ]
  }
];

// ==================== [뉴스 투자 예측 30개 MOCK 데이터] ====================

export const mockPredictionNews: PredictionNews[] = [
  {
    id: 'pnews-1',
    title: '삼성전자, 세계 최초 6세대 HBM4 샘플 출하 성공 발표',
    content: '삼성전자가 차세대 고대역폭메모리(HBM4) 개발을 완료하고 주요 AI 빅테크 고객사에 샘플을 출하했다고 밝혔습니다. 이에 따른 반도체 부문 실적 개선 기대감이 높아집니다.',
    company: '삼성전자',
    source: '한국경제 (산업)',
    stockTicker: '005930',
    difficulty: '쉬움',
    createdAt: '10분 전',
    actualChange: 25,
    actualDirection: '상승',
    explanation: 'HBM4 선점 성공 소식은 시장의 최대 우려를 해소하며 반도체 투자심리를 대폭 개선시켰습니다 (+2.5% 상승).',
    category: '반도체',
    chartData: [
      { time: '09:00', price: 72000 },
      { time: '11:00', price: 73200 },
      { time: '13:00', price: 73500 },
      { time: '15:30', price: 73800 },
    ]
  },
  {
    id: 'pnews-2',
    title: 'SK하이닉스, 미국 인디애나 첨단 패키징 공장 기공식 개최',
    content: 'SK하이닉스가 5조 원 규모의 미국 차세대 메모리 패키징 신공장 건설에 착수했습니다. 차세대 HBM 수요 대응력을 강화할 예정입니다.',
    company: 'SK하이닉스',
    source: '연합뉴스 (경제)',
    stockTicker: '000660',
    difficulty: '쉬움',
    createdAt: '30분 전',
    actualChange: 18,
    actualDirection: '상승',
    explanation: '글로벌 테크 공급망에서의 우위 입지를 다지면서 외국인 순매수가 유입되었습니다 (+1.8% 상승).',
    category: '반도체'
  },
  {
    id: 'pnews-3',
    title: 'NAVER, 생성형 AI 서비스 분기 매출 사상 최대 달성',
    content: '네이버의 하이퍼클로바X 기반 B2B 솔루션 및 검색 광고 매출이 급증하면서 2분기 영업이익이 전년 대비 22% 증가했습니다.',
    company: 'NAVER',
    source: '매일경제 (IT)',
    stockTicker: '035420',
    difficulty: '쉬움',
    createdAt: '1시간 전',
    actualChange: 32,
    actualDirection: '상승',
    explanation: 'AI 수익화 모델 검증 완료 소식에 기관 매수세가 집중되었습니다 (+3.2% 상승).',
    category: 'IT/플랫폼'
  },
  {
    id: 'pnews-4',
    title: '카카오, 수사당국 법적 리스크 재부각 및 일부 서비스 장애 발생',
    content: '카카오의 주요 경영진 관련 사법 리스크가 이어지는 가운데, 핵심 플랫폼 서비스의 연속 접속 장애가 발생하며 사용자 불만이 가중되었습니다.',
    company: '카카오',
    source: '조선비즈',
    stockTicker: '035720',
    difficulty: '쉬움',
    createdAt: '2시간 전',
    actualChange: -28,
    actualDirection: '하락',
    explanation: '플랫폼 신뢰도 저하와 리스크 우려로 주가가 급락했습니다 (-2.8% 하락).',
    category: 'IT/플랫폼'
  },
  {
    id: 'pnews-5',
    title: 'LG에너지솔루션, 북미 완성차업체와 10조 원 규모 배터리 공급 계약 체결',
    content: 'LG엔솔이 스텔란티스와의 합작법인을 통해 북미 시장용 대규모 LFP/차세대 배터리 장기 공급 계약을 성공시켰습니다.',
    company: 'LG에너지솔루션',
    source: '서울경제',
    stockTicker: '373220',
    difficulty: '쉬움',
    createdAt: '3시간 전',
    actualChange: 45,
    actualDirection: '상승',
    explanation: '전기차 캐즘 속에서도 대규모 신규 수주를 확보하면서 강력한 호재로 작용했습니다 (+4.5% 상승).',
    category: '2차전지'
  },
  {
    id: 'pnews-6',
    title: '현대차, 미국 자율주행 택시 서비스 호조로 영업이익률 10% 돌파',
    content: '현대차 및 기아의 하이브리드 차량 호조와 자율주행 모빌리티 자회사 로보택시 사업 성과로 주주환원율이 대폭 확대될 방침입니다.',
    company: '현대차',
    source: '한국경제 (자동차)',
    stockTicker: '005380',
    difficulty: '쉬움',
    createdAt: '4시간 전',
    actualChange: 21,
    actualDirection: '상승',
    explanation: '실적 모멘텀과 배당 확대 소식으로 매수세가 가팔랐습니다 (+2.1% 상승).',
    category: '자동차'
  },
  {
    id: 'pnews-7',
    title: '테슬라, 완전자율주행(FSD) 한국 및 유럽 승인 연기 가능성 보도',
    content: '규제당국 승인 절차 지연 우려로 로보택시 글로벌 확장 속도에 차질이 생길 수 있다는 미디어 보고서가 나왔습니다.',
    company: '테슬라',
    source: '블룸버그통신',
    stockTicker: 'TSLA',
    difficulty: '보통',
    createdAt: '5시간 전',
    actualChange: -19,
    actualDirection: '하락',
    explanation: '승인 연기 소식으로 자율주행 소프트웨어 프리미엄 기대감이 일부 반납되었습니다 (-1.9% 하락).',
    category: '해외주식'
  },
  {
    id: 'pnews-8',
    title: '애플, 신형 아이폰 AI 기능 무료 제공 기간 연장 및 신제품 예약 폭주',
    content: 'Apple Intelligence 신규 기능 발표 이후 차세대 아이폰 사전 예약 물량이 사상 최고치를 기록했습니다.',
    company: '애플',
    source: '로이터통신',
    stockTicker: 'AAPL',
    difficulty: '보통',
    createdAt: '6시간 전',
    actualChange: 15,
    actualDirection: '상승',
    explanation: '교체 주기 도래와 AI 기능 기대감이 실적 기대치를 올려놓았습니다 (+1.5% 상승).',
    category: '해외주식'
  },
  {
    id: 'pnews-9',
    title: '셀트리온, 미국 FDA로부터 짐펜트라 신규 적응증 승인 획득',
    content: '자가면역질환 치료제 짐펜트라의 미국 시장 적응증이 추가되며 처방 PBM 등재가 대폭 늘어날 예정입니다.',
    company: '셀트리온',
    stockTicker: '068270',
    difficulty: '보통',
    createdAt: '7시간 전',
    actualChange: 38,
    actualDirection: '상승',
    explanation: '미국 바이오시밀러 및 신약 직판 매출 성장에 대한 강한 확신을 주었습니다 (+3.8% 상승).',
    category: '바이오'
  },
  {
    id: 'pnews-10',
    title: 'POSCO홀딩스, 글로벌 철강 수요 침체 우려로 분기 실적 하회',
    content: '중국산 저가 철강재 유입과 글로벌 건설 경기 둔화 영향으로 포스코홀딩스의 영업이익이 시장 전망치를 밑돌았습니다.',
    company: 'POSCO홀딩스',
    stockTicker: '005490',
    difficulty: '보통',
    createdAt: '8시간 전',
    actualChange: -14,
    actualDirection: '하락',
    explanation: '철강 시황 약세 지속 우려로 하락 마감했습니다 (-1.4% 하락).',
    category: '철강/소재'
  },
  {
    id: 'pnews-11',
    title: '에코프로, 리튬 가격 반등 호재 속 2차전지 양극재 수주 확대',
    content: '국제 리튬 가격이 오랜 하락세를 멈추고 반등세를 보이자 에코프로비엠 및 에코프로의 재고자산 평가 손실 우려가 해소되고 있습니다.',
    company: '에코프로',
    stockTicker: '086520',
    difficulty: '보통',
    createdAt: '9시간 전',
    actualChange: 52,
    actualDirection: '상승',
    explanation: '원자재 가격 반등에 따른 마진 개선 기대로 숏커버링 물량이 유입되었습니다 (+5.2% 상승).',
    category: '2차전지'
  },
  {
    id: 'pnews-12',
    title: 'KB금융, 밸류업 프로그램 이행으로 자사주 3천억 원 소각 결정',
    content: 'KB금융지주가 주주가치 제고를 위해 추가 자사주 매입 및 소각 조치를 발표하며 당기순이익 주당 가치를 상승시켰습니다.',
    company: 'KB금융',
    stockTicker: '105560',
    difficulty: '쉬움',
    createdAt: '10시간 전',
    actualChange: 29,
    actualDirection: '상승',
    explanation: '적극적인 주주환원 정책이 금융주 전반의 상승세를 이끌었습니다 (+2.9% 상승).',
    category: '금융'
  },
  {
    id: 'pnews-13',
    title: '한화에어로스페이스, 루마니아와 1조 원 규모 K9 자주포 수출 본계약',
    content: 'K-방산의 유럽 시장 지배력이 공고해지면서 수주 잔고가 사상 최고치를 경신했습니다.',
    company: '한화에어로스페이스',
    stockTicker: '012450',
    difficulty: '쉬움',
    createdAt: '11시간 전',
    actualChange: 41,
    actualDirection: '상승',
    explanation: '방산 수주 모멘텀 지속으로 외국인 강한 순매수가 이어졌습니다 (+4.1% 상승).',
    category: '방산'
  },
  {
    id: 'pnews-14',
    title: '크래프톤, 배틀그라운드 신규 맵 및 IP 컬래버레이션으로 매출 폭발',
    content: '글로벌 게임 플랫폼 동시 접속자 수가 전년 대비 30% 증가하며 신작 공백기 우려를 말끔히 씻어냈습니다.',
    company: '크래프톤',
    stockTicker: '259960',
    difficulty: '보통',
    createdAt: '12시간 전',
    actualChange: 26,
    actualDirection: '상승',
    explanation: '안정적인 라이브 게임 매출로 실적 호조세를 이어갔습니다 (+2.6% 상승).',
    category: '게임'
  },
  {
    id: 'pnews-15',
    title: '삼성바이오로직스, 4공장 완공 후 5공장 조기 가동 추진',
    content: '글로벌 제약사들의 위탁생산(CMO) 장기 계약이 쇄도하면서 생산 능력이 가동률 100%에 육박했습니다.',
    company: '삼성바이오로직스',
    stockTicker: '207940',
    difficulty: '보통',
    createdAt: '13시간 전',
    actualChange: 17,
    actualDirection: '상승',
    explanation: '바이오 CMO 절대 강자로서의 압도적 영업이익률이 조명되었습니다 (+1.7% 상승).',
    category: '바이오'
  },
  {
    id: 'pnews-16',
    title: '기아, 인도 시장 전용 소형 SUV 흥행 성패 속 고환율 수혜 기대',
    content: '원달러 환율 상승에 따른 수출 환차익 증가로 기아의 해외 매출액 증가가 상쇄 효과를 톡톡히 보고 있습니다.',
    company: '기아',
    stockTicker: '000270',
    difficulty: '쉬움',
    createdAt: '14시간 전',
    actualChange: 12,
    actualDirection: '상승',
    explanation: '환율 호재와 하이브리드 고마진 차종 비중 확대로 상승했습니다 (+1.2% 상승).',
    category: '자동차'
  },
  {
    id: 'pnews-17',
    title: '마이크로소프트, 코파일럿 B2B 구독료 인상 발표에도 기업 고객 유지율 98%',
    content: '기업용 AI 자원 비용 보전을 위해 구독 가격을 인상했으나 기업들의 이탈이 거의 나타나지 않는 독점적 지위를 확인했습니다.',
    company: '마이크로소프트',
    stockTicker: 'MSFT',
    difficulty: '어려움',
    createdAt: '15시간 전',
    actualChange: 22,
    actualDirection: '상승',
    explanation: '가격 결정력(Pricing Power)을 입증하며 AI 소프트웨어 매출의 고성장이 정당화되었습니다 (+2.2% 상승).',
    category: '해외주식'
  },
  {
    id: 'pnews-18',
    title: '삼성SDI, 전고체 배터리 파일럿 라인 수율 안정화 지연 루머 소동',
    content: '출처 불분명한 라인 수율 지연 루머가 인터넷 커뮤니티에 유포되면서 장 초반 매도 물량이 쏟아졌으나 사측은 사실무근이라 해명했습니다.',
    company: '삼성SDI',
    stockTicker: '006400',
    difficulty: '어려움',
    createdAt: '16시간 전',
    actualChange: -11,
    actualDirection: '하락',
    explanation: '해명 공시에도 불구하고 불확실성 경계감에 약보합으로 장을 마감했습니다 (-1.1% 하락).',
    category: '2차전지'
  },
  {
    id: 'pnews-19',
    title: '신한지주, 홍콩 H지수 ELS 배상 완료 및 건전성 지표 우수 평가',
    content: '금융감독원 가이드라인에 따른 일회성 충당금 설정이 마무리되며 하반기 분기 배당금이 증액될 가능성이 커졌습니다.',
    company: '신한지주',
    stockTicker: '055550',
    difficulty: '보통',
    createdAt: '17시간 전',
    actualChange: 16,
    actualDirection: '상승',
    explanation: '일회성 불확실성 소멸 및 주주환원 재개 기대감으로 유입되었습니다 (+1.6% 상승).',
    category: '금융'
  },
  {
    id: 'pnews-20',
    title: 'ASML, 한국 반도체 클러스터 내 첨단 EUV 재질 지원센터 준공',
    content: '네덜란드 반도체 노광장비 기업 ASML이 화성캠퍼스를 정식 가동하면서 국내 메모리 반도체 공정 지원이 한층 원활해집니다.',
    company: '삼성전자 / SK하이닉스',
    stockTicker: 'ASML',
    difficulty: '어려움',
    createdAt: '18시간 전',
    actualChange: 9,
    actualDirection: '상승',
    explanation: 'EUV 장비 수급 및 유지보수 효율화 호재로 반도체 소부장 생태계 전반에 긍정 영향을 주었습니다 (+0.9% 상승).',
    category: '반도체'
  },
  {
    id: 'pnews-21',
    title: 'HD현대중공업, 친환경 암모니아 운반선 4척 8천억 원 규모 수주',
    content: '선가 상승 흐름 속 고부가가치 친환경 선박 수주가 지속되며 조선업 장기 슈퍼사이클 정점에 진입했습니다.',
    company: 'HD현대중공업',
    stockTicker: '329180',
    difficulty: '보통',
    createdAt: '19시간 전',
    actualChange: 34,
    actualDirection: '상승',
    explanation: '고선가 수주 물량 건조 본격화로 신조선가 지수가 최고치를 갱신했습니다 (+3.4% 상승).',
    category: '조선'
  },
  {
    id: 'pnews-22',
    title: '카카오페이, 글로벌 결제 네트워크 연동 확대에 따른 거래액 증가',
    content: '해외 여행객 증가와 유럽/아시아 주요국 현지 결제망 연동으로 해외 결제 매출이 전년 대비 80% 늘어났습니다.',
    company: '카카오페이',
    stockTicker: '377300',
    difficulty: '어려움',
    createdAt: '20시간 전',
    actualChange: 13,
    actualDirection: '상승',
    explanation: '해외 결제 수수료 이익이 커지며 핀테크 플랫폼 수익구조 다변화 평가를 받았습니다 (+1.3% 상승).',
    category: 'IT/핀테크'
  },
  {
    id: 'pnews-23',
    title: 'SK텔레콤, AI 데이터센터(AIDC) 사업 진출로 신성장동력 확보',
    content: '통신 본업의 안정적 현금흐름을 바탕으로 엔비디아 GPU 기반 AI 클라우드 인프라 대관 사업을 개시합니다.',
    company: 'SK텔레콤',
    stockTicker: '017670',
    difficulty: '쉬움',
    createdAt: '21시간 전',
    actualChange: 14,
    actualDirection: '상승',
    explanation: '고배당 주주환원 안전판과 AI 모멘텀이 더해져 상승세를 시현했습니다 (+1.4% 상승).',
    category: '통신'
  },
  {
    id: 'pnews-24',
    title: '엔씨소프트, 신작 MMORPG 글로벌 테스트 평점 호불호 갈려',
    content: '기대를 모은 대작 신작의 글로벌 알파 테스트 결과 과금 구조와 자동 전투 시스템에 대한 해외 게이머 평가가 엇갈렸습니다.',
    company: '엔씨소프트',
    stockTicker: '036570',
    difficulty: '보통',
    createdAt: '22시간 전',
    actualChange: -23,
    actualDirection: '하락',
    explanation: '초기 흥행 성공에 대한 불확실성이 커지면서 기관 실망 매물이 출시되었습니다 (-2.3% 하락).',
    category: '게임'
  },
  {
    id: 'pnews-25',
    title: 'HMM, 홍해 해상 물류 불안 지속으로 컨테이너 운임지수(SCFI) 급등',
    content: '글로벌 공급망 우회항로 이용 장기화로 해상 운임 지수가 고공행진하며 해운사 영업이익 추정치가 대폭 상향되었습니다.',
    company: 'HMM',
    stockTicker: '011200',
    difficulty: '어려움',
    createdAt: '1일 전',
    actualChange: 36,
    actualDirection: '상승',
    explanation: '운임 지수 폭등에 따른 단기 실적 대폭 호조 기대감으로 매수세가 몰렸습니다 (+3.6% 상승).',
    category: '물류/해운'
  },
  {
    id: 'pnews-26',
    title: '두산에너빌리티, 체코 신규 원전 건설 사업 우선협상대상자 선정 발표',
    content: '30조 원 규모의 유럽 대형 원전 수주전에서 한국 컨소시엄이 최종 승리하면서 주기기 공급을 맡은 두산에너빌리티가 최대 수혜를 입습니다.',
    company: '두산에너빌리티',
    stockTicker: '034020',
    difficulty: '쉬움',
    createdAt: '1일 전',
    actualChange: 68,
    actualDirection: '상승',
    explanation: '역대급 해외 원전 수출 성과 소식에 상한가에 가까운 폭등을 기록했습니다 (+6.8% 상승).',
    category: '원전/에너지'
  },
  {
    id: 'pnews-27',
    title: '아모레퍼시픽, 미국 및 일본 뷰티 시장 매출이 중국 역성장 완전 상쇄',
    content: '코스알엑스 인수 효과와 서구권 K-뷰티 열풍으로 해외 영업이익 구조가 탈중국화에 성공했습니다.',
    company: '아모레퍼시픽',
    stockTicker: '090430',
    difficulty: '보통',
    createdAt: '1일 전',
    actualChange: 28,
    actualDirection: '상승',
    explanation: '체질 개선 성공에 대한 긍정적 분석 리포트가 잇따라 발행되었습니다 (+2.8% 상승).',
    category: '화장품/소비재'
  },
  {
    id: 'pnews-28',
    title: 'CJ제일제당, 비비고 만두 및 K-푸드 글로벌 유통망 확대로 해외 매출 60% 진입',
    content: '미국 대형 마트 체인 입점 확대와 유럽 현지 공장 가동으로 글로벌 식품 사업 이익률이 사상 최고 수준에 도달했습니다.',
    company: 'CJ제일제당',
    stockTicker: '097950',
    difficulty: '보통',
    createdAt: '1일 전',
    actualChange: 19,
    actualDirection: '상승',
    explanation: '음식료 업종 내 해외 비중 높은 우수 기업으로 주목받았습니다 (+1.9% 상승).',
    category: '식품/소비재'
  },
  {
    id: 'pnews-29',
    title: '하이브, BTS 멤버 전원 전역 카운트다운 및 월드투어 기대감 고조',
    content: '완전체 활동 재개 시점이 다가옴에 따라 음원, 굿즈, 공연 플랫폼 위버스(Weverse) 실적 폭발 전망이 가시화되고 있습니다.',
    company: '하이브',
    stockTicker: '352820',
    difficulty: '쉬움',
    createdAt: '2일 전',
    actualChange: 42,
    actualDirection: '상승',
    explanation: '엔터주 대장주로서의 실적 불확실성 해소 및 강한 밸류에이션 재평가가 나타났습니다 (+4.2% 상승).',
    category: '엔터/미디어'
  },
  {
    id: 'pnews-30',
    title: 'S-Oil, 국제 유가 변동성 확대로 정제마진 일시 축소 하락',
    content: '산유국 감산 규모 축소 우려와 글로벌 석유 제품 재고 증가로 정유사들의 핵심 수익 지표인 복합 정제마진이 하락했습니다.',
    company: 'S-Oil',
    stockTicker: '010950',
    difficulty: '어려움',
    createdAt: '2일 전',
    actualChange: -17,
    actualDirection: '하락',
    explanation: '정제마진 축소로 분기 이익 감익 우려가 반영되며 약세를 보였습니다 (-1.7% 하락).',
    category: '정유/화학'
  }
];

export const mockQuests: Quest[] = [
  {
    id: 'q1',
    title: '첫 브리핑 학습하기',
    description: '오늘의 주요 시사 뉴스 1개를 끝까지 읽고 4컷 만화 학습을 완료하세요.',
    category: '학습',
    currentCount: 1,
    targetCount: 1,
    rewardXp: 100,
    isCompleted: true,
    icon: 'book',
  },
  {
    id: 'q2',
    title: '주가 방향 맞추기 3회',
    description: '뉴스 투자 예측에서 주가 상승/하락 방향 예측을 3회 성공하세요.',
    category: '투자 예측',
    currentCount: 2,
    targetCount: 3,
    rewardXp: 150,
    isCompleted: false,
    icon: 'trending-up',
  },
  {
    id: 'q3',
    title: '주가 방향 맞추기 10회',
    description: '뉴스 투자 예측에서 주가 상승/하락 방향 예측을 10회 성공하세요.',
    category: '투자 예측',
    currentCount: 4,
    targetCount: 10,
    rewardXp: 400,
    isCompleted: false,
    icon: 'award',
  },
  {
    id: 'q4',
    title: '포인트 예측 성공 3회',
    description: '변동폭 포인트 예측에서 오차 5이내 정답을 3회 달성하세요.',
    category: '투자 예측',
    currentCount: 1,
    targetCount: 3,
    rewardXp: 200,
    isCompleted: false,
    icon: 'target',
  },
  {
    id: 'q5',
    title: '뉴스 예측 참여 20회',
    description: '총 20개의 뉴스 투자 예측에 도전해보세요.',
    category: '투자 예측',
    currentCount: 6,
    targetCount: 20,
    rewardXp: 500,
    isCompleted: false,
    icon: 'bar-chart-2',
  },
  {
    id: 'q6',
    title: '연속 정답 5회 달성',
    description: '뉴스 예측에서 연속으로 5회 정답을 맞춰보세요.',
    category: '투자 예측',
    currentCount: 2,
    targetCount: 5,
    rewardXp: 350,
    isCompleted: false,
    icon: 'zap',
  },
  {
    id: 'q7',
    title: '커뮤니티 소통왕',
    description: '다른 유저의 만화 요약 게시글에 댓글 2개 이상을 작성하세요.',
    category: '소통',
    currentCount: 1,
    targetCount: 2,
    rewardXp: 100,
    isCompleted: false,
    icon: 'message-square',
  }
];

export const mockBadges: Badge[] = [
  {
    id: 'b1',
    title: '첫발걸음',
    icon: 'footprints',
    isUnlocked: true,
    description: '첫 번째 시사 뉴스를 완독했습니다.',
  },
  {
    id: 'b2',
    title: '족집게 예측가',
    icon: 'target',
    isUnlocked: true,
    description: '포인트 예측 오차 0을 1회 이상 달성했습니다.',
  },
  {
    id: 'b3',
    title: '반도체 마스터',
    icon: 'cpu',
    isUnlocked: false,
    description: '반도체 분야 뉴스와 예측을 10회 완료했습니다.',
  },
  {
    id: 'b4',
    title: '연속 스트라이크',
    icon: 'flame',
    isUnlocked: false,
    description: '뉴스 투자 예측 5연속 정답을 달성했습니다.',
  },
];

export const mockRankings: UserRank[] = [
  {
    rank: 1,
    name: '투자의신김버핏',
    level: 12,
    xp: 2840,
    streak: 14,
    badges: 8,
    avatar: '김',
    predictionScore: 1250,
    totalScore: 4090,
  },
  {
    rank: 2,
    name: '차트위자드',
    level: 10,
    xp: 2100,
    streak: 9,
    badges: 6,
    avatar: '차',
    predictionScore: 980,
    totalScore: 3080,
  },
  {
    rank: 3,
    name: '주식왕라이언',
    level: 5,
    xp: 680,
    streak: 3,
    badges: 3,
    avatar: '라',
    predictionScore: 240,
    totalScore: 920,
  },
  {
    rank: 4,
    name: '슬기로운개미',
    level: 3,
    xp: 320,
    streak: 1,
    badges: 2,
    avatar: '슬',
    predictionScore: 150,
    totalScore: 470,
  }
];

export const mockStocks: StockItem[] = [
  {
    id: 'st-1',
    name: '삼성전자',
    ticker: '005930',
    price: '73,800',
    currency: 'KRW',
    changeRate: '+2.5%',
    isUp: true,
    category: '반도체',
  },
  {
    id: 'st-2',
    name: 'SK하이닉스',
    ticker: '000660',
    price: '188,500',
    currency: 'KRW',
    changeRate: '+1.8%',
    isUp: true,
    category: '반도체',
  },
  {
    id: 'st-3',
    name: 'LG에너지솔루션',
    ticker: '373220',
    price: '382,000',
    currency: 'KRW',
    changeRate: '+4.5%',
    isUp: true,
    category: '2차전지',
  },
  {
    id: 'st-4',
    name: 'NAVER',
    ticker: '035420',
    price: '172,400',
    currency: 'KRW',
    changeRate: '+3.2%',
    isUp: true,
    category: 'IT/플랫폼',
  },
  {
    id: 'st-5',
    name: '카카오',
    ticker: '035720',
    price: '41,200',
    currency: 'KRW',
    changeRate: '-2.8%',
    isUp: false,
    category: 'IT/플랫폼',
  }
];

export const defaultStockList = mockStocks;
export const mockStockData = mockStocks[0];

